peacecorps/paygov/urls.py
from django.conf.urls import patterns, url

from paygov.views import data, results


urlpatterns = patterns(
    '',
    url(r'^data/?$', data, name='data'),
    url(r'^results/?$', results, name='results')
    # url(r'^settlement/?$', settlement)
)

peacecorps/peacecorps/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.conf.urls.static import static
from django.views.generic import RedirectView

from peacecorps import api, views
from peacecorps.cache import midterm_cache, shortterm_cache

_slug = r'(?P<slug>[a-zA-Z0-9_-]+)'

apipatterns = patterns(
    '',
    url(r'^project/' + _slug + r'/$',
        shortterm_cache(api.ProjectDetail.as_view()), name='project_detail'),
    url(r'^project/' + _slug + r'/payment/$',
        api.ProjectDonation.as_view(), name='project_payment'),
    url(r'^fund/' + _slug + r'/payment/$',
        api.FundDonation.as_view(), name='fund_payment'),
)


urlpatterns = patterns(
    '',
    url(r'^donate/$', midterm_cache(views.donate_landing),
        name='donate landing'),
    url(r'^donate/projects-funds/$',
        midterm_cache(views.donate_projects_funds),
        name='donate projects funds'),
    url(r'^donate/projects-funds/memorial/$',
        midterm_cache(views.memorial_funds), name='donate memorial funds'),
    url(r'^donate/faq/$', midterm_cache(views.FAQs.as_view()),
        name='donate faqs'),

    url(r'^donate/fund/' + _slug + r'/$',
        midterm_cache(views.fund_detail), name='donate campaign'),
    # not cached so the values are up-to-date
    url(r'^donate/fund/' + _slug + r'/payment/$',
        views.campaign_form, name='campaign form'),
    url(r'^donate/fund/' + _slug + r'/success/$',
        views.CampaignReturn.as_view(
            template_name='donations/campaign_success.jinja'),
        name='campaign success'),
    url(r'^donate/fund/' + _slug + r'/failure/$',
        views.failure, {'redirect_to': 'donate campaign'},
        name='campaign failure'),

    url(r'^donate/project/' + _slug + r'/$',
        midterm_cache(views.donate_project), name='donate project'),
    # not cached so the values are up-to-date
    url(r'^donate/project/' + _slug + r'/payment/$',
        views.project_form, name='project form'),
    url(r'^donate/project/' + _slug + r'/success/$',
        views.ProjectReturn.as_view(
            template_name='donations/project_success.jinja'),
        name='project success'),
    url(r'^donate/project/' + _slug + r'/failure/$',
        views.failure, {'redirect_to': 'donate project'},
        name='project failure'),

    url(r'^favicon\.ico$',
        RedirectView.as_view(url=settings.STATIC_URL + "favicon.ico")),

    url(r'^api/', include(apipatterns, namespace='api')),

    url(r'^donate/api/v1/projects/',
        views.ProjectListAPI.as_view(),
        name='projects api'),

    url(r'^donate/api/v1/campaigns/country',
        views.CountryCampaignListAPI.as_view(),
        name='campaigns api'),

    url(r'^donate/paygov-callback-test/',
        views.paygov_callback_test, name='donate paygovcallbacktest'),

)


handler404 = views.four_oh_four


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += patterns('', url(r'^404/$', handler404))

if apps.is_installed('paygov'):
    urlpatterns += patterns(
        '', url(r'^callback/', include('paygov.urls', namespace='paygov')))

if apps.is_installed('contenteditor'):
    urlpatterns += patterns(
        '',
        url(r'^admin/', include('contenteditor.urls')),
        url(r'^admin/sirtrevor/', include('sirtrevor.urls')))

peacecorps/peacecorps/models.py
# @todo split this file up, perhaps into smaller apps?
from datetime import timedelta, datetime
import json
import tempfile
import os

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Sum
from django.template.loader import render_to_string as django_render
from django.utils import timezone
from django.utils.text import slugify
from django.core.files.storage import default_storage
from localflavor.us.models import USPostalCodeField
from localflavor.us.us_states import USPS_CHOICES
from sirtrevor.fields import SirTrevorField
from PIL import Image
from tinymce.models import HTMLField

from peacecorps.fields import GPGField, BraveSirTrevorField
from peacecorps.util import svg


NAME_LENGTH = 120   # Consistent length for project/account/fund names
ABBR_TO_STATE = dict(USPS_CHOICES)


def imagesave(description):
    """Saves images from Sir Trevor fields to the media model."""
    if not description:
        # if description is empty for any reason, it has no images.
        return False

    description = json.loads(description)

    for block in description['data']:
        if block['type'] == 'image508':
            imagepath = block['data']['file']['path']

            desc = block['data']['image_description']

            thisimage = Media.objects.filter(file=imagepath).first()
            if thisimage is None:
                thisimage = Media(file=imagepath)
            thisimage.title = block['data']['image_title']
            thisimage.mediatype = Media.IMAGE
            thisimage.description = desc

            thisimage.save()

    return True


class AbstractHTMLMixin(object):
    """Adds the abstract_html method. Assumes the object has an abstract and
    description field, where the description field is sir-trevor json. Also
    assumes that the object has a primary_url method (for the read-more
    link)."""

    def abstract_plaintext(self, include_shortened=False):
        """If an explicit abstract is present, return it. Otherwise, return
        the first paragraph of the description"""
        text = ''
        shortened = False
        if self.abstract:
            text = self.abstract
        elif self.description:
            for block in json.loads(self.description)['data']:
                if block.get('type') == 'text':
                    data = block['data']
                    # Naive string shortener
                    if len(data['text']) > settings.ABSTRACT_LENGTH:
                        trimmed = data['text'][:settings.ABSTRACT_LENGTH]
                        trimmed = trimmed[:trimmed.rindex(' ')]
                        text = trimmed
                        shortened = True
                    else:
                        text = data['text']
                    break
        if include_shortened:
            return text, shortened
        else:
            return text

    def abstract_html(self, read_more_link=False):
        """Take the plaintext and run it through a sir trevor template"""
        text, shortened = self.abstract_plaintext(include_shortened=True)
        context = {'text': text, 'shortened': shortened}
        if shortened and read_more_link:
            context['more_url'] = self.primary_url()
        return django_render('donations/includes/abstract.html', context)


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(
            published=True)


class AccountManager(models.Manager):
    """We more or less always want to aggregate the dynamic number of
    donations, so add it to the default query set"""
    def get_queryset(self):
        return super(AccountManager, self).get_queryset().annotate(
            dynamic_total=Sum('donations__amount'))


class Account(models.Model):
    COUNTRY = 'coun'
    MEMORIAL = 'mem'
    OTHER = 'oth'
    PROJECT = 'proj'
    SECTOR = 'sec'
    CATEGORY_CHOICES = (
        (COUNTRY, 'Country'),
        (SECTOR, 'Sector'),
        (MEMORIAL, 'Memorial'),
        (OTHER, 'Other'),
        (PROJECT, 'Project'),
    )

    name = models.CharField(max_length=NAME_LENGTH, unique=True,
        help_text="The name of the project or fund.")
    code = models.CharField(max_length=25, primary_key=True,
        help_text="The accounting code for the project or fund.")
    current = models.IntegerField(
        default=0,
        help_text="Amount from donations (excluding real-time contributions), \
        in cents.")
    goal = models.IntegerField(
        blank=True, null=True,
        help_text="For PCPP projects, the funding goal, excluding community \
        contribution.")
    # @todo does it make sense for this to default zero?
    community_contribution = models.IntegerField(blank=True, null=True, 
        help_text="For PCPP projects, the amount of community contributions, \
        in cents.")
    category = models.CharField(
        max_length=10, choices=CATEGORY_CHOICES, help_text="The type of \
        account.")

    objects = AccountManager()

    def __str__(self):
        return '%s' % (self.code)

    def total_donated(self):
        """Total amount raised via donations (including real-time). Does not
        include community contributions"""
        if not hasattr(self, 'dynamic_total'):
            agg = self.donations.aggregate(Sum('amount'))
            self.dynamic_total = agg['amount__sum']
        return self.current + (self.dynamic_total or 0)

    def total_raised(self):
        """Total amount raised, including donations and community
        contributions"""
        return self.total_donated() + (self.community_contribution or 0)

    def total_cost(self):
        """Total cost of whatever we are raising funds for. This includes the
        donations goal and the community contribution"""
        if self.goal:
            return self.goal + (self.community_contribution or 0)
        else:
            return 0

    def percent_raised(self):
        """What percent of the total cost has been raised through donations
        and community contributions?"""
        total_cost = self.total_cost()
        if total_cost:
            return round(self.total_raised() * 100 / total_cost, 2)
        else:
            return 0

    def percent_community(self):
        """What percent of the total cost was community contributions?"""
        total_cost = self.total_cost()
        if total_cost:
            return round(self.community_contribution * 100 / total_cost, 2)
        else:
            return 0

    def funded(self):
        if self.goal and self.total_donated() >= self.goal:
            return True
        else:
            return False

    def remaining(self):
        """This will be expanded later, and may involve more complicated
        calculations. As such, we don't want it to be a property"""
        if self.goal:
            return self.goal - self.total_donated()
        else:
            return 0

    def project_or_fund(self):
        """Given an account, we may need to get back to the project or
        campaign/fund associated"""
        if self.category == Account.PROJECT:
            return self.project_set.first()
        else:
            return self.campaign_set.first()


# @todo: Probably worth renaming
class Campaign(models.Model, AbstractHTMLMixin):
    """
    A campaign is any fundraising effort. Campaigns collect donations to a
    separate account that can be distributed to projects (sector, country,
    special, and memorial funds, the general fund).
    """
    COUNTRY = 'coun'
    GENERAL = 'gen'
    MEMORIAL = 'mem'
    OTHER = 'oth'
    SECTOR = 'sec'
    CAMPAIGNTYPE_CHOICES = (
        (COUNTRY, 'Country'),
        (GENERAL, 'General'),
        (SECTOR, 'Sector'),
        (MEMORIAL, 'Memorial'),
        (OTHER, 'Other'),
    )

    name = models.CharField(max_length=NAME_LENGTH, 
        help_text="The title for the associated campaign.")
    account = models.ForeignKey('Account', unique=True, 
        help_text="The accounting code for this campaign.")
    campaigntype = models.CharField(
        max_length=10, choices=CAMPAIGNTYPE_CHOICES,
        help_text="The type of campaign.",
        verbose_name="Campaign Type")
    icon = models.ForeignKey(
        'Media', null=True, blank=True, related_name="campaign-icons",
        help_text="Used for Memorial Funds. Typically a picture of the \
        volunteer. Should be 120px tall and 120px wide, with the focus of the \
        photo centered.",
        verbose_name="Memorial Fund Volunteer Image")
    featured_image = models.ForeignKey(
        'Media', null=True, blank=True, related_name="campaign-headers",
        help_text="A large landscape image for use at the top of the campaign \
        page. Should be 1100px wide and 454px tall.")
    tagline = models.CharField(
        max_length=140,
        help_text="If the campaign is featured on the home page, this text is \
        used as the description of the campaign.",
        blank=True, null=True)
    call = models.CharField(
        max_length=50, help_text="If the campaign is featured on the home \
        page, this text is used in the button as a Call to Action.",
        blank=True, null=True)
    slug = models.SlugField(
        help_text="Auto-generated. Used for the campaign page URL.",
        max_length=NAME_LENGTH, unique=True)
    description = BraveSirTrevorField(help_text="A rich text description. \
        of the campaign.")
    featuredprojects = models.ManyToManyField('Project', blank=True, null=True)
    country = models.ForeignKey(
        'Country', related_name="campaign", blank=True, null=True, unique=True,
        help_text="If the campaign is related to a specific country, the ID \
        of that country.")
    abstract = models.TextField(blank=True, null=True, max_length=256,
        help_text="A shorter description, used for quick views of the \
        campaign.")

peacecorps/peacecorps/templates/donations/campaign_success.jinja
{% extends "donations/base.jinja" %}

{% block og_description %}{{ campaign.abstract_plaintext() }}{% endblock %}
{% block og_image %}{% if campaign.account.code == 'LGL-GEN' %}{{ static('peacecorps/img/og_lgl.jpg') }}{% else %}{{ super() }}{% endif %}{% endblock %}


{% block content_class %}thankyou{% endblock %}

{% block content %}
<section class="section t--black u-clearfix">
  <div class="blurb">
    {% if request.GET.donor_name %}
      <h1>Thank you, {{ request.GET.donor_name }}!</h1>
    {% else %}
      <h1>Thank you!</h1>
    {% endif %}
    <h4>Your donation to the {{campaign.name}} will go to help our volunteer
      projects.</h4>
  </div>
  <div class="blurb blurb--flatten_t u-clearfix u-align_c">
  Please note, if you chose ACH Bank Check as your payment method, it may take
  up to two days for your donation to appear on the site.
  </div>
  <div class="blurb blurb--flatten_t u-clearfix u-align_c">
    <h4 class="t-title--3">Tell Your Friends</h4>
    <ul class="main_nav">
      <li class="main_nav__link">
        <a target="_blank"
              href="//www.facebook.com/sharer/sharer.php?u={{ share_url(request, override=share_override or None) | urlencode }}"
              >Facebook</a></li>
      <li class="main_nav__link">
        <a target="_blank"
              href="//twitter.com/intent/tweet?text={{ share_tweet() | urlencode }}"
              >Twitter</a></li>
      <li class="main_nav__link">
        <a target="_blank"
          href="mailto:?subject={{ share_subject() | urlencode }}&amp;body={{ share_text() | urlencode }}">
            Email</a></li>
    </ul>
  </div>
</section>

<section class="section section__content t--black
      full_banner full_banner--width full_banner--neutral">
  <div class="inset inset--lg">
    <a href="{{url("donate campaign", slug=campaign.slug)}}"
        class="t-title--4 t-single_nav">
      <i class="fa fa-angle-left icon icon--text"></i>
      View Fund</a>
  </div>
  <div class="section__content u-clearfix">
    <div class="inset inset--sm">
      {# @TODO Photo #}
      <h4 class="t-title--4">You Helped Support This</h4>
      <h3 class="t--secondary">{{ campaign.name }}</h2>
      {{ campaign.description.html|safe }}
    </div>
  </div>
</section>

<script type="text/javascript">
  dataLayer.push({
       'event': 'eventTracker', 'eventCat': 'Donation',
'eventAct':'{{ campaign.name }}', 'eventLbl': '1',
'eventVal':0,
       'ecommerce': {
       'currencyCode': 'USD',
          'purchase': {
       'actionField': {
          'id': '{{ campaign.account }}',
          'affiliation': 'Peace Corps Donations', 
          'revenue': '1',
          'tax':'0',
          'shipping': '0',
          'coupon': ''
          },
          'products': [
              {
                'name': '{{ campaign.name }}',
                'id': '{{ campaign.account }}', 
                'price': '1',
                'brand': '',
                'category': 'Donation',
                'variant': '',
                'quantity': 1,
                'coupon': ''
              },
          ]
      } 
    }
  });
</script>
{% endblock %}

peacecorps/peacecorps/templates/donations/checkout_base.jinja
{% extends "donations/base.jinja" %}

{% block content_class %}donate-form{% endblock %}


{% block content %}
<div class="full_bg full_bg--top full_bg--sm" style="background-image:
    url('{{ static("peacecorps/img/default_top.png") }}');
  ">
</div>
  <section class="blurb">
    {% if project %}
      {% include "donations/includes/project-top.jinja" %}
    {% else %}
      {# todo #}
    {% endif %}
      <div class="u-align_l inset--sm t--gray--2">
        <h3 class="t-heading--stylized">You are donating</h3><br>
        <h1 class="t-heading--stylized t--secondary">
          {{ humanize_cents(payment_amount) }}</h1>
        <h4 class="t-heading--stylized">to</h4><br>
        <h3 class="t-heading--stylized">
          <strong>{{ project.title or campaign.name }}</strong></h3>
      </div>
  </section>

  <section class="section form
      full_banner full_banner--width full_banner--neutral full_banner--flush">
    <div class="inset inset--lg">
      {% block form_content %}{% endblock %}
      <section class="section">
        <div class="form__field form__field--single">
          <p class="t-body--sm form__text t-break">OMB no. 0420-XXXX<br>
          Expiration date: TBD
          </p>

          <h4 class="form__text">This is a Secure Transaction</h4>
          <p class="t-body--sm form__text t-break">
          The secure server software (SSL) that processes Peace Corps donations is
          the industry standard and among the best software available today for
          secure commerce transactions. It encrypts all of your personal data
          including credit card number, name, and address, so that it cannot be
          read as the information travels over the Internet. You can tell when you
          are protected by encryption — the lock or key at the bottom of your
          browser changes color or is no longer broken.
          </p>

          <h4 class="form__text">Burden Statement</h4>
          <p class="t-body--sm form__text">
            Public reporting burden for this collection of information is estimated to average 10 minutes per response. This includes the time for reviewing instructions and completing the information. This is voluntary information collection. An agency may not conduct or sponsor, and persons are not required to respond to, a collection of information unless it displays a currently valid OMB control number. Send comments regarding this burden estimate or any other aspect of this collection of information, including suggestions for reducing this burden, to: the FOIA Officer, Peace Corps, 1111 20th Street NW, 2nd Floor, Washington, D.C. 20526.
          </p>

        </div>
      </section>
    </div>
  </section>
{% endblock %}

peacecorps/peacecorps/templates/donations/checkout_form.jinja
{% extends "donations/checkout_base.jinja" %}

{% if pay_gov_alert.is_active %}
{% include "donations/includes/paygov-alert.jinja" %}
{% endif %}

{% block form_content %}
    <form action="" method="post" class="js-form section__content"
          data-ajax-url="{{ajax_url}}">
      {% csrf_token %}
      <input type="hidden" name="payment_amount"
             value="{{request.GET.payment_amount}}" />
      <fieldset class="inset--lg">
        <legend><h2>Your information</h2>
          <p class="t-body--md">(so we can send you a tax receipt)</p>
        </legend>

        <div class="form__field form__field--single">
            {{form.is_org.errors}}
            <div class="form__field__input"
                aria-controls="collapsible-isorganization">
              {{form.is_org}}</div>
            <label for="id_is_org" class="form__field__label">
              {{form.is_org.label}}</label>
        </div>

        <div class="form__field js-formSwitch"
            data-switch-id="collapsible-isorganization"
            data-switch-on="true">
          {{form.organization_name.errors}}
          <label for="id_organization_name" class="form--required
              form__field__label">
            organization name</label>
          <div class="form__field__input">{{form.organization_name}}</div>
        </div>

        <div class="form__field js-formSwitch"
            data-switch-id="collapsible-isorganization"
            data-switch-on="true">
          {{form.organization_contact.errors}}
          <label for="id_organization_contact" class="form--required
            form__field__label">
              organization contact</label>
          <div class="form__field__input">{{form.organization_contact}}</div>
        </div>

        <div class="form__field js-formSwitch"
              data-switch-id="collapsible-isorganization"
              data-switch-on="false">
            {{form.payer_name.errors}}
            <label for="id_payer_name" class="form--required form__field__label">
              full name</label>
            <div class="form__field__input">{{form.payer_name}}</div>
        </div>

        <div class="form__field">
            {{form.billing_address.errors}}
            <label for="id_billing_address" class="form--required form__field__label">
              street address</label>
            <div class="form__field__input">{{form.billing_address}}</div>
        </div>

        <div class="form__field">
            {{form.billing_address.errors}}
            <label for="id_billing_address_extra"
                class="form__field__label">
              address cont.(optional)</label>
            <div class="form__field__input">{{form.billing_address_extra}}</div>
        </div>

        <div class="form__field">
            {{form.billing_city.errors}}
            <label for="id_billing_city" class="form--required form__field__label">
              city</label>
            <div class="form__field__input field--sm">{{form.billing_city}}</div>
        </div>

        <div class="form__field">
            {{form.billing_state.errors}}
            <label for="id_billing_state" class="form--required form__field__label">
              state</label>
            <div class="form__field__input">{{form.billing_state}}</div>
        </div>

        <div class="form__field">
            {{form.billing_zip.errors}}
            <label for="id_billing_zip" class="form--required form__field__label">
              zip code</label>
            <div class="form__field__input field--sm">{{form.billing_zip}}</div>
        </div>

        <div class="form__field">
            {{form.country.errors}}
            <label for="id_country" class="form--required form__field__label">
              country</label>
            <div class="form__field__input">{{form.country}}</div>
        </div>

        <div class="form__field">
            {{form.email.errors}}
            <label class="form__field__label" for="id_email">email</label>
            <div class="form__field__input">{{form.email}}</div>
        </div>


        <div class="form__field">
            {{form.phone_number.errors}}
            <label class="form__field__label" for="id_phone_number">phone</label>
            <div class="form__field__input">{{form.phone_number}}</div>
        </div>
      </fieldset>

      <fieldset class="inset--lg">
        <legend><h2>Payment Method</h2></legend>
        <div class="form__field">
          {{form.payment_type.errors}}
          <label for='id_payment_type' class="form--required form__field__label">
            </label>
          <div class="form__field__input">
            {{form.payment_type}}
            <a href="{{ url('donate faqs') }}#not-online">Pay by check?</a>
          </div>
        </div>
      </fieldset>

      <fieldset class="inset--lg">
        <legend><h2>Options</h2></legend>

        <div class="form__field form__field--single">
            {{form.dedication.errors}}
            <div class="form__field__input js-formCollapsible"
                aria-controls="collapsible-dedication">
              {{form.dedication}}
            </div>
            <label for="id_dedication" class="form__field__label">
              I wish to donate in honor or in
              memory of someone.
            </label>
        </div>
        <fieldset class="js-collapsibleToggle" id="collapsible-dedication"
          aria-hidden="true">
            <legend>Dedication Information</legend>
            <div  class="form__field">
                {{form.dedication_name.errors}}
                <label class="form__field__label" for='id_dedication_name'>
                  name</label>
                <div class="form__field__input">{{form.dedication_name}}</div>
            </div>

            <div class="form__field">
                {{form.dedication_type.errors}}
                <label class="form__field__label" for='dedication_type'>
                  type of dedication</label>
                <div class="form__field__input" id="dedication_type">
                {{form.dedication_type}}</div>
            </div>

            <legend><p class="honoree_swap form__text">
                Send the honoree a letter so they
                know you were thinking of them: </p></legend>

            <div id="dedication_contact_wrapper">
                {{form.dedication_contact.errors}}
                <label class="form__field__label" for='id_dedication_contact'>
                  family contact</label>
                <div class="form__field__input">{{form.dedication_contact}}</div>
            </div>

            <div class="form__field">
                {{form.dedication_email.errors}}
                <label class="form__field__label" for='id_dedication_email'>
                  email</label>
                <div class="form__field__input">{{form.dedication_email}}</div>
            </div>

            <div class="form__field">
                {{form.dedication_address.errors}}
                <label class="form__field__label" for='id_dedication_address'>
                  mailing address</label>
                <div class="form__field__input">
                  {{form.dedication_address}}</div>
            </div>

            <div class="form__field">
                {{form.card_dedication.errors}}
                <label class="form__field__label form__field__label--align_t"
                    for='id_card_dedication'>
                  message</label>
                <div class="form__field__input">{{form.card_dedication}}</div>
            </div>

            <div class="form__field">
                {{form.dedication_consent.errors}}
                <label for="id_dedication_consent"
                    class="form__field__label form__field__label--align_t">
                  information consent</label>

                <ul id="id_dedication_consent" class="form__field__input">
                <li><label for="id_dedication_consent_0" class="honoree_swap
                      form__field--together">
                    <input checked="checked" id="id_dedication_consent_0"
                     name="dedication_consent" type="radio"
                     value="yes-dedication-consent" />
                    I authorize the Peace Corps to make my name and contact
                    information available to the honoree.
                    </label>
                </li>
                <li><label for="id_dedication_consent_1" class="honoree_swap
                      form__field--together">
                    <input id="id_dedication_consent_1" name="dedication_consent"
                     type="radio" value="no-dedication-consent" />
                    I do not authorize the Peace Corps to make my name and
                    contact information available to the honoree.
                    </label>
                </li>
                </ul>
            </div>
        </fieldset>

        <div class="form__field form__field--single">
            {{form.email_consent.errors}}
            <div class="form__field__input">{{form.email_consent}}</div>
            <label for="id_email_consent" class="form__field__label">
              Please send me updates on this project and others.
            </label>
        </div>

        <div class="form__field form__field--single">
          {{form.information_consent.errors}}
          <div class="form__field__input">{{ form.information_consent }}</div>
          <label for="id_information_consent" class="form__field__label">
            Make my contact info available to the volunteer
          </label>
        </div>

        <div class="form__field">
          {{form.comments.errors}}
          <label for='id_comments' class="form__field__label
              form__field__label--align_t">
            Please use this box if you want to send a message of encouragement
            to this project's volunteer.
          </label>
          <div class="form__field__input">
            {{form.comments}}
          </div>
        </div>

        <div class="form__field form__field--single">
          {{form.interest_conflict.errors}}
          <div class="form__field__input">
            {{form.interest_conflict}}
          </div>
          <label for="id_interest_conflict" class="form__field__label">
            I'm doing business with the Peace Corps
          </label>
          <p class="t-body--md form__text">
            If you, your business, your employer, or an immediate family
            member is currently doing business, or seeking to do business with
            Peace Corps, or otherwise have business or financial interests
            that may be affected by Peace Corps please check the box above and
            contact the Peace Corps Partnership Program at 202.692.2170 or
            <a href="mailto:donate@peacecorps.gov">donate@peacecorps.gov</a>. Note: Serving as a Peace Corps Volunteer is
            not a business or financial interest.
          </p>
        </div>

        {% for hidden in form.hidden_fields() %}
            {{hidden}}
        {% endfor %}

      </fieldset>

      <section class="section inset--lg separator separator--t">
        <div class="form__field form__field--single">

          <div class="u-align_c form__text section__content">
            <button type="submit" class="button button--primary js-submit">
              Confirm information</button>
          </div>
          
          <p class="form__text">
            NOTE: We use Pay.gov as our trusted secure payment processor. We’ll
            send you on to there and bring you back when you finish.</p>
        </div>
      </section>
    </form>
{% endblock %}